export const copy: Record<string, string> = {
  add: "Add",
  addSidebarTag: "Add sidebar tag",
  addSidebarTagDescription:
    "Save a tag in the sidebar so you can filter matching bug notes later.",
  addSidebarTagTitle: "Add tag",
  addTag: "Add tag",
  all: "All",
  backTo: "Back to",
  bugActions: "Bug actions",
  bugNotebook: "Bug Notebook",
  cancel: "Cancel",
  cardId: "Card ID",
  cardProvider: "Card provider",
  cardTitle: "Card title",
  cardUrl: "Card URL",
  changePassword: "Change password",
  chooseNewPassword: "Choose a new password",
  clear: "Clear",
  close: "Close",
  closeForm: "Close form",
  closeMemoryPanel: "Close memory panel",
  closeSidebar: "Close sidebar",
  create: "Create",
  createAccount: "Create account",
  createBugDescription:
    "Capture the full debugging context while it is still fresh.",
  createBugTitle: "New bug note",
  createdAt: "Created",
  currentPassword: "Current password",
  currentPasswordRequiredForEmail:
    "Current password is required to change email.",
  dangerZone: "Danger zone",
  delete: "Delete",
  deleteAccount: "Delete account",
  deleteAccountDescription:
    "Permanently delete your account and all bug notes.",
  deleteBugConfirm: "This action cannot be undone.",
  deleteConfirm: "Are you sure you want to delete your account?",
  deleteFailed: "Account could not be deleted.",
  deletePasswordPlaceholder: "Type your current password",
  deletePasswordRequired: "Current password is required.",
  developerFallback: "Developer",
  draft: "Draft",
  draftPlural: "Drafts",
  edit: "Edit",
  editBugDescription:
    "Update the note fields, tags, stack and linked card details.",
  editBugTitle: "Edit bug note",
  email: "Email",
  emailDescription: "Update the email address used to sign in.",
  emailSaveFailed: "Email could not be updated.",
  emailSaved: "Email updated.",
  generateResetLink: "Generate reset link",
  generating: "Generating...",
  investigating: "Investigating",
  investigatingPlural: "Investigating",
  landingDescription:
    "Capture every hard bug, response, cause and solution in one searchable engineering memory.",
  landingEyebrow: "Private debugging memory",
  landingTitle: "Turn repeated bugs into reusable knowledge.",
  linkedCard: "Linked card",
  linkedCards: "Linked cards",
  linksAndMemory: "Links and memory",
  listRecordCount: "{count} records",
  logout: "Sign out",
  memory: "Memory",
  myBugs: "My bugs",
  name: "Name",
  namePlaceholder: "Jane Developer",
  newEmail: "New email",
  newPassword: "New password",
  noBugNotes: "No bug notes yet.",
  noCard: "No card",
  noConnection: "No connection found.",
  noLinkedCard: "No linked card yet.",
  noMemoryNote: "No memory note yet.",
  noNote: "No note",
  noRelatedNotes: "No related notes.",
  noResponse: "No response recorded.",
  noSearchResults: "No matching bug notes.",
  noSelectedBug: "No bug selected",
  noTagsInNote: "No tags in this note.",
  noTagsYet: "No tags yet.",
  observations: "Observations",
  older: "Older",
  openCard: "Open card",
  openDemo: "Open demo",
  openMemoryPanel: "Open memory panel",
  openResetLink: "Open reset link",
  openSidebar: "Open sidebar",
  password: "Password",
  passwordDescription: "Change your account password.",
  passwordPlaceholder: "At least 8 characters",
  passwordRequired: "Current and new password are required.",
  passwordResetFailed: "Password could not be reset.",
  passwordSaved: "Password updated.",
  passwordSaveFailed: "Password could not be updated.",
  passwordUpdatedSignIn: "Password updated. You can sign in now.",
  personalDebugMemory: "Personal debug memory",
  priority: "Priority",
  problem: "Problem",
  product: "Product",
  profile: "Profile",
  profileSaveFailed: "Profile could not be saved.",
  profileSaved: "Profile saved.",
  project: "Project",
  quickContext: "Quick context for this bug",
  relatedNotes: "Related notes",
  rememberedIt: "Remembered it?",
  removeFromSidebar: "Remove from sidebar",
  removeTagFromNote: "Remove tag from note",
  resetGenerated: "Reset link generated.",
  resetPasswordDescription: "Enter your email and generate a reset link.",
  resetPasswordInfo: "Set a new password for your account.",
  resetPasswordTitle: "Reset password",
  resetRequestFailed: "Reset request failed.",
  response: "Response",
  revisitNote: "Revisit note",
  resolved: "Resolved",
  role: "Role",
  save: "Save",
  saveNewPassword: "Save new password",
  saveProfile: "Save profile",
  saving: "Saving...",
  selectBugFromList: "Select a bug from the list to inspect it.",
  settings: "Settings",
  settingsDescription: "Manage your profile, email and password.",
  sidebarTagAlreadyExists: "This tag already exists.",
  signIn: "Sign in",
  solution: "Solution",
  solutionSaved: "Solution saved",
  solved: "Resolved",
  sort: "Sort",
  sortedLatest: "Latest first",
  sortedOldest: "Oldest first",
  stack: "Stack",
  status: "Status",
  summary: "Summary",
  tagName: "Tag name",
  tags: "Tags",
  thisWeek: "This week",
  title: "Title",
  today: "Today",
  updatedAt: "Updated",
  userFallback: "User",
  workspace: "Workspace",
  workspaceStats: "{total} bugs, {resolved} resolved",
};
